stages:
  - mavenbuild
  - maventest

maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - cd Backend
    - mvn package

maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd Backend
    - mvn test
  artifacts:
    paths:
      - Backend/target/*.jar
