AWSTemplateFormatVersion: '2010-09-09'
Resources:
  DockerRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${AWS::StackName}-repo
  ECSCluster:
    Type: AWS:ECS:Cluster
    Properties:
    