name: main

on:
  push:
    paths:
      - Backend/**
      - .github/workflows/**
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy-stack:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::520392043186:role/GHActionDeployer
          aws-region: us-east-2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Package with Maven
        run: |
          mvn package

      - name: Build and push Docker image
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 520392043186.dkr.ecr.us-east-2.amazonaws.com
          docker build -t rmd-ecrrepository-1z0wtutfnuo8 .
          docker tag rmd-ecrrepository-1z0wtutfnuo8:latest 520392043186.dkr.ecr.us-east-2.amazonaws.com/rmd-ecrrepository-1z0wtutfnuo8:${{ github.run_number }}
          docker push 520392043186.dkr.ecr.us-east-2.amazonaws.com/rmd-ecrrepository-1z0wtutfnuo8:${{ github.run_number }}
      
      - name: Deploy to AWS
        run: |
          aws cloudformation deploy --template-file cloudformation.yaml --stack-name rmd --capabilities CAPABILITY_NAMED_IAM --parameter-overrides "KeyName=jacob@xps" "CidrAccess=0.0.0.0/0" "DomainName=rmd.duba.sh" "HostedZoneId=Z03106041US4JX4MGA9TK" ImageTag=${{ github.run_number }} 
